language: python
python:
  - 3.6
cache: pip3
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - pip3 install -r requirements.txt
script:
    - py.test --cov=app
after_success:
    - coveralls